name: Continuous Integration

on:
  push:
    branches:
      - main
    paths:
      - "data/**/*.json"
      - "schemas/**/*.json"
  pull_request:
    branches:
      - main
    paths:
      - "data/**/*.json"
      - "schemas/**/*.json"

jobs:

  validate:
    needs: []
    runs-on: ubuntu-latest
    steps:
      - name: "Set up GitHub Actions"
        uses: actions/checkout@v2
      - name: "Setup node"
        uses: actions/setup-node@v2
        with:
          node-version: 15
      - name: "Install dependencies"
        run: npm install
      - name: "Validate JSON schemas"
        run: make compile
      - name: "Validate JSON data"
        run: make validate
