name: Continuous Integration

on:
  push:
    branches:
      - main
    paths:
      - "data/**/*.json"
      - "schemas/**/*.json"
  pull_request:
    branches:
      - main
    paths:
      - "data/**/*.json"
      - "schemas/**/*.json"


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:

  validate:
    needs: []
    runs-on: ubuntu-latest
    steps:
      - name: "Set up GitHub Actions"
        uses: actions/checkout@v3
      - name: "Set up Node"
        uses: actions/setup-node@v3
        with:
          node-version: 15
      - name: "Install dependencies"
        run: npm install --no-optional
      - name: "Validate JSON schemas"
        run: make compile
      - name: "Validate JSON data"
        run: make validate
